spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3307/optimization
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://bottlemoon.me:3307/optimization
    username: admin
    password: admin

  jpa:
    properties:
      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        show_sql: true

    defer-datasource-initialization: true

logging:
  level:
    p6spy: info
